import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "./context/appContext";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <AppProvider>{children} </AppProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
